### ISSUE TITLE
Containers are not public

### ISSUE THREAD

**Issue by pschichtel** [docspell/docker#5]
@eikek I don't think I have the permission to change this, so asking you:

https://github.com/docspell/docker/pkgs/container/joex is currently set to provide (it's been created through github actions) and should be changed to public.

see https://github.com/eikek/docspell/issues/2504#issuecomment-2354892222

**Comment by eikek** [comment]
Hi @pschichtel, I never used github image repository. So you mean I should set this repository to "public", right? let me see how to do that

**Comment by pschichtel** [comment]
yes. if you go to the link from the issue description, there should be a settings button somewhere

**Comment by eikek** [comment]
Yes found it, thanks! I had to first enable this in the organization settings. It should be public now
